/**
 * EDITABLE WEDDING CONTENT
 * Update names, times, contact details, bank information, and bilingual copy here.
 */
export type Language = 'es' | 'en';

export const wedding = {
  names: {
    first: 'Inés Camara',
    second: 'Guillermo Martinez',
    short: 'Inés & Guille',
  },
  dateISO: '2026-09-26',
  venue: 'Finca El Venero',
  address: 'C. el Venero, s/n, 05100 Navaluenga, Ávila',
  mapsUrl:
    'https://www.google.com/maps/search/?api=1&query=Finca+El+Venero%2C+Calle+el+Venero+s%2Fn%2C+05100+Navaluenga%2C+Avila',
  venueUrl: 'https://fincaelvenero.com/',
  pinterestUrl: 'https://pin.it/uHrJXg56k',
  bank: {
    holder: 'Guillermo Martinez Fernandez',
    iban: 'ES60 1465 0100 91 1775535838',
  },
  contact: {
    names: 'Inés & Guille',
    detail: 'Teléfonos por confirmar · Phone numbers to be confirmed',
  },
  content: {
    es: {
      languageName: 'Español',
      nav: {
        label: 'Navegación principal',
        place: 'El lugar',
        rides: 'Compartir coche',
        agenda: 'Agenda',
        info: 'Información',
        gift: 'Regalo',
        language: 'Seleccionar idioma',
      },
      hero: {
        eyebrow: 'Nos casamos',
        connector: 'y',
        date: '26 · 09 · 2026',
        dateLong: 'Sábado, 26 de septiembre de 2026',
        location: 'Navaluenga · Ávila',
        scroll: 'Ver toda la info',
      },
      place: {
        label: '01 · El lugar',
        title: 'Os esperamos en Finca El Venero.',
        description:
          'La finca está junto al río Alberche y a pocos minutos del centro de Navaluenga. Tiene tres casas rurales, jardín y espacio de sobra para pasar el fin de semana juntos.',
        addressLabel: 'Dirección',
        maps: 'Abrir en Google Maps',
        venueWeb: 'Web de la finca',
      },
      arrival: {
        label: 'Cómo llegar',
        routes: [
          {
            title: 'Desde Madrid',
            text: 'Toma la M-501 hacia San Martín de Valdeiglesias, continúa por la N-403 dirección Ávila y toma el desvío AV-902 hacia Navaluenga.',
          },
          {
            title: 'Últimos metros',
            text: 'En el GPS busca “Finca El Venero” o C. el Venero, s/n. Evita seleccionar Venero Claro, que está al otro lado del pueblo.',
          },
        ],
        parkingTitle: 'Aparcamiento',
        parkingText: 'Hay aparcamiento gratuito dentro de la finca.',
        maps: 'Iniciar ruta',
      },
      carShare: {
        label: '02 · Compartir el viaje',
        title: '¿Tienes sitio? ¿Te falta coche?',
        intro: 'Aquí podéis ofrecer plazas o encontrar a alguien que salga cerca. La ida y la vuelta se organizan por separado, porque los planes cambian después de unas copas.',
        identifyTitle: 'Primero, dinos quién eres',
        identifyText: 'Pon tu nombre o el de tu familia. Este dispositivo recordará tus viajes y solicitudes.',
        name: 'Nombre o familia',
        namePlaceholder: 'Ana & Pablo',
        phone: 'Teléfono',
        phonePlaceholder: 'Opcional',
        enter: 'Ver los viajes',
        privacy: 'Importante: usa zonas aproximadas. La dirección exacta, siempre por privado.',
        greeting: 'Hola',
        signOut: 'Cambiar de invitado',
        offer: 'Ofrecer plazas',
        editRide: 'Editar viaje',
        toWedding: 'Ida a la boda',
        fromWedding: 'Vuelta de la boda',
        areaTo: 'Zona de salida',
        areaFrom: 'Zona de destino',
        areaPlaceholder: 'Chamberí, Pozuelo, Boadilla…',
        date: 'Fecha',
        time: 'Hora',
        seats: 'Plazas disponibles',
        notes: 'Notas',
        notesPlaceholder: 'Punto de encuentro aproximado, espacio para equipaje…',
        saveRide: 'Publicar viaje',
        updateRide: 'Guardar cambios',
        cancelEdit: 'Cancelar edición',
        available: 'Viajes disponibles',
        empty: 'Todavía no hay viajes en esta dirección. Si tienes hueco, inaugura la lista.',
        requestSeats: 'Plazas que necesitas',
        request: 'Solicitar plazas',
        ownRide: 'Tu viaje',
        edit: 'Editar',
        cancelRide: 'Cancelar viaje',
        myRequests: 'Tus solicitudes',
        noRequests: 'Todavía no has solicitado ninguna plaza.',
        incoming: 'Solicitudes recibidas',
        noIncoming: 'No tienes solicitudes pendientes.',
        accept: 'Aceptar',
        reject: 'Rechazar',
        cancelRequest: 'Cancelar solicitud',
        requested: 'Pendiente',
        accepted: 'Aceptada',
        full: 'Completo',
        contact: 'Contacto',
        loading: 'Cargando viajes…',
        retry: 'Volver a intentar',
        confirmCancelRide: '¿Quieres cancelar este viaje? Las solicitudes pendientes también se cancelarán.',
        created: 'Viaje publicado.',
        updated: 'Viaje actualizado.',
        rideCancelled: 'Viaje cancelado.',
        requestSent: 'Solicitud enviada.',
        requestCancelled: 'Solicitud cancelada.',
        requestAccepted: 'Solicitud aceptada.',
        requestRejected: 'Solicitud rechazada.',
      },
      agenda: {
        label: '03 · Agenda',
        title: 'Un fin de semana para celebrar juntos.',
        days: [
          {
            day: 'Viernes',
            date: '25 septiembre',
            events: [
              {
                time: '19:00',
                title: 'Preboda',
                description: 'Cena informal, copas y primera ronda de saludos. Venid como estéis.',
              },
            ],
          },
          {
            day: 'Sábado',
            date: '26 septiembre',
            events: [
              {
                time: '14:30',
                title: 'Ceremonia',
                description: 'Empezamos a las 14:30 en la finca. Llegad con un poco de margen.',
              },
              {
                time: 'Después',
                title: 'Celebración',
                description: 'Cóctel, comida, brindis y baile. A partir de aquí, mirad menos el reloj.',
              },
            ],
          },
        ],
      },
      dress: {
        label: '04 · Dress code',
        title: 'Elegantes, relajados y cómodos.',
        description:
          'La idea es ir guapos sin ir de gala. Ropa ligera, cómoda y con personalidad: hay jardín, sobremesa y unas cuantas horas de baile.',
        notes: [
          'Ellas: vestidos fluidos, monos o conjuntos con pantalón. Colores, estampados y accesorios con personalidad, adelante.',
          'Ellos: camisa de cuello abierto o polo de punto con pantalón de lino o chino. Ligero, sencillo y en tonos naturales; chaqueta solo si apetece.',
          'Un único consejo: calzado cómodo. Hay jardín y, con suerte, muchas horas de baile. Para la noche, trae una capa ligera.',
          'Blanco, marfil y looks completamente crema: se los dejamos a la novia.',
        ],
        boardLabel: 'La inspiración',
        boardTitle: 'Campo, color y baile.',
        boardText: 'Es una referencia, no deberes: tonos naturales, prendas con movimiento y cero rigidez.',
        boardCta: 'Ver moodboard en Pinterest',
        palette: ['Oliva', 'Arena', 'Terracota', 'Rosa empolvado'],
      },
      info: {
        label: '05 · Información de interés',
        title: 'Lo que conviene saber.',
        cards: [
          {
            number: '01',
            title: 'Alojamiento',
            text: 'La finca tiene tres casas. Si duermes allí, te diremos más adelante cuál te toca.',
          },
          {
            number: '02',
            title: 'Entrada y salida',
            text: 'Check-in el viernes desde las 15:00. El domingo hay salida tardía para que nos despidamos tranquilamente.',
          },
          {
            number: '03',
            title: 'Desayuno',
            text: 'El sábado habrá desayuno para quienes duermen en la finca.',
          },
          {
            number: '04',
            title: 'Piscina',
            text: 'Hay piscina. Si duermes en la finca, mete bañador. Luego no digas que no avisamos.',
          },
          {
            number: '05',
            title: 'Niños',
            text: 'Los niños son bienvenidos, aunque, si podéis, os recomendamos venir sin ellos: queremos que comáis, brindéis y bailéis sin horarios. Si vienen, estarán siempre bajo la responsabilidad de sus padres o tutores.',
          },
          {
            number: '06',
            title: 'Tiempo',
            text: 'A finales de septiembre puede hacer bueno de día y fresco de noche. Recuerda que estamos al pie de la sierra de Gredos. Mira la previsión y trae una capa ligera.',
          },
          {
            number: '07',
            title: 'Transporte',
            text: 'No habrá transporte organizado. Venid en coche y organizad la vuelta con tiempo. Podéis usar la sección Compartir coche.',
          },
          {
            number: '08',
            title: 'Contacto',
            text: 'Si algo no queda claro, escribid a Inés o Guille. Añadiremos aquí los teléfonos de contacto.',
          },
        ],
      },
      gift: {
        label: '06 · Regalo',
        title: 'Si queréis hacernos un regalo.',
        message:
          'Con venir y celebrarlo con nosotros es suficiente. Si además queréis hacernos un regalo, os dejamos la cuenta aquí para ponéroslo fácil.',
        holder: 'Titular',
        iban: 'IBAN',
        copy: 'Copiar número de cuenta',
        copied: 'Número de cuenta copiado',
      },
      footer: {
        closing: 'Nos vemos en Navaluenga',
        sourceNote: 'Traed ganas de pasarlo bien.',
      },
    },
    en: {
      languageName: 'English',
      nav: {
        label: 'Primary navigation',
        place: 'The place',
        rides: 'Car sharing',
        agenda: 'Schedule',
        info: 'Information',
        gift: 'Gift',
        language: 'Select language',
      },
      hero: {
        eyebrow: 'We are getting married',
        connector: 'and',
        date: '26 · 09 · 2026',
        dateLong: 'Saturday, 26 September 2026',
        location: 'Navaluenga · Ávila, Spain',
        scroll: 'See all the details',
      },
      place: {
        label: '01 · The place',
        title: 'See you at Finca El Venero.',
        description:
          'The estate is by the Alberche River, a few minutes from central Navaluenga. It has three houses, a garden and plenty of room for us to spend the weekend together.',
        addressLabel: 'Address',
        maps: 'Open in Google Maps',
        venueWeb: 'Venue website',
      },
      arrival: {
        label: 'Getting there',
        routes: [
          {
            title: 'From Madrid',
            text: 'Take the M-501 towards San Martín de Valdeiglesias, continue on the N-403 towards Ávila, then take the AV-902 turn-off to Navaluenga.',
          },
          {
            title: 'The final stretch',
            text: 'Search for “Finca El Venero” or C. el Venero, s/n in your GPS. Avoid choosing Venero Claro, which is on the other side of the village.',
          },
        ],
        parkingTitle: 'Parking',
        parkingText: 'Free parking is available inside the estate.',
        maps: 'Start route',
      },
      carShare: {
        label: '02 · Share the journey',
        title: 'Got a spare seat? Need a lift?',
        intro: 'Offer a spare seat or find someone leaving near you. Outbound and return trips are separate, because plans tend to change after a few drinks.',
        identifyTitle: 'First, tell us who you are',
        identifyText: 'Enter your name or family name. This device will remember your journeys and requests.',
        name: 'Name or family',
        namePlaceholder: 'Ana & Pablo',
        phone: 'Phone',
        phonePlaceholder: 'Optional',
        enter: 'See the journeys',
        privacy: 'Important: use approximate areas. Always share exact addresses privately.',
        greeting: 'Hi',
        signOut: 'Change guest',
        offer: 'Offer seats',
        editRide: 'Edit journey',
        toWedding: 'Journey to the wedding',
        fromWedding: 'Journey from the wedding',
        areaTo: 'Departure area',
        areaFrom: 'Destination area',
        areaPlaceholder: 'Chamberí, Pozuelo, Boadilla…',
        date: 'Date',
        time: 'Time',
        seats: 'Available seats',
        notes: 'Notes',
        notesPlaceholder: 'Approximate meeting point, luggage space…',
        saveRide: 'Publish journey',
        updateRide: 'Save changes',
        cancelEdit: 'Cancel editing',
        available: 'Available journeys',
        empty: 'No journeys in this direction yet. If you have room, start the list.',
        requestSeats: 'Seats you need',
        request: 'Request seats',
        ownRide: 'Your journey',
        edit: 'Edit',
        cancelRide: 'Cancel journey',
        myRequests: 'Your requests',
        noRequests: 'You have not requested any seats yet.',
        incoming: 'Requests received',
        noIncoming: 'You have no pending requests.',
        accept: 'Accept',
        reject: 'Reject',
        cancelRequest: 'Cancel request',
        requested: 'Pending',
        accepted: 'Accepted',
        full: 'Full',
        contact: 'Contact',
        loading: 'Loading journeys…',
        retry: 'Try again',
        confirmCancelRide: 'Cancel this journey? Pending requests will also be cancelled.',
        created: 'Journey published.',
        updated: 'Journey updated.',
        rideCancelled: 'Journey cancelled.',
        requestSent: 'Request sent.',
        requestCancelled: 'Request cancelled.',
        requestAccepted: 'Request accepted.',
        requestRejected: 'Request rejected.',
      },
      agenda: {
        label: '03 · Schedule',
        title: 'A weekend to celebrate together.',
        days: [
          {
            day: 'Friday',
            date: '25 September',
            events: [
              {
                time: '19:00',
                title: 'Pre-wedding gathering',
                description: 'Informal dinner, drinks and the first round of hellos. Come as you are.',
              },
            ],
          },
          {
            day: 'Saturday',
            date: '26 September',
            events: [
              {
                time: '14:30',
                title: 'Ceremony',
                description: 'We start at 14:30 at the estate. Please arrive with a little time to spare.',
              },
              {
                time: 'Afterwards',
                title: 'Celebration',
                description: 'Cocktails, lunch, toasts and dancing. From here on, check the time less often.',
              },
            ],
          },
        ],
      },
      dress: {
        label: '04 · Dress code',
        title: 'Elegant, relaxed and comfortable.',
        description:
          'The idea is to look great without going full formal. Keep it light, comfortable and personal: there is a garden, a long lunch and several hours of dancing.',
        notes: [
          'For women: fluid dresses, jumpsuits or trouser separates. Colour, prints and accessories with personality are all welcome.',
          'For men: an open-collar shirt or knitted polo with linen trousers or chinos. Light, simple and naturally toned; add a jacket only if you feel like it.',
          'One piece of advice: comfortable shoes. There is a garden and, hopefully, many hours of dancing. Bring a light layer for the evening.',
          'Please leave white, ivory and head-to-toe cream to the bride.',
        ],
        boardLabel: 'The inspiration',
        boardTitle: 'Countryside, colour, dancing.',
        boardText: 'A reference, not homework: natural tones, clothes with movement and zero stiffness.',
        boardCta: 'View moodboard on Pinterest',
        palette: ['Olive', 'Sand', 'Terracotta', 'Dusty pink'],
      },
      info: {
        label: '05 · Useful information',
        title: 'Things worth knowing.',
        cards: [
          {
            number: '01',
            title: 'Accommodation',
            text: 'The estate has three houses. If you are staying, we will tell you which one is yours later.',
          },
          {
            number: '02',
            title: 'Check-in & check-out',
            text: 'Check-in is Friday from 15:00. Sunday check-out is late so we can say goodbye without rushing.',
          },
          {
            number: '03',
            title: 'Breakfast',
            text: 'Breakfast will be provided on Saturday for everyone staying at the estate.',
          },
          {
            number: '04',
            title: 'Swimming pool',
            text: 'There is a pool. If you are staying at the estate, pack swimwear. You have now been warned.',
          },
          {
            number: '05',
            title: 'Children',
            text: 'Children are welcome, although, if you can, we recommend making it an adults’ weekend: we want you to eat, toast and dance without watching the clock. If they come, they remain under their parents’ or guardians’ responsibility.',
          },
          {
            number: '06',
            title: 'Weather',
            text: 'Late September can be warm by day and cool at night. Remember that we are at the foot of the Sierra de Gredos. Check the forecast and bring a light layer.',
          },
          {
            number: '07',
            title: 'Transport',
            text: 'There will be no organised transport. Come by car and plan the return trip early. You can use the Car sharing section.',
          },
          {
            number: '08',
            title: 'Contact',
            text: 'If anything is unclear, message Inés or Guille. We will add the contact numbers here.',
          },
        ],
      },
      gift: {
        label: '06 · Gift',
        title: 'If you would like to give us something.',
        message:
          'Coming and celebrating with us is enough. If you would also like to give us a gift, the account is here to make it easy.',
        holder: 'Account holder',
        iban: 'IBAN',
        copy: 'Copy account number',
        copied: 'Account number copied',
      },
      footer: {
        closing: 'See you in Navaluenga',
        sourceNote: 'Bring your best party mood.',
      },
    },
  },
} as const;
